# docker-compose.yml
# yaml
version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./users:/app/users
    environment:
      - FLASK_ENV=production
      - ENCRYPTION_KEY='84-7WpbNp9Y2h5aDQ-jqphkcZ7Uj3d5I4C5b09vrm9U='
